/**
 * Функции написанные здесь пригодятся на последующих уроках
 * С помощью этих функций мы будем добавлять элементы в список для проверки динамической загрузки
 * Поэтому в идеале чтобы функции возвращали случайные данные, но в то же время не абракадабру.
 * В целом сделайте так, как вам будет удобно.
 * */

/**
 * Нужно создать тип Category, он будет использоваться ниже.
 * Категория содержит
 * - id (строка)
 * - name (строка)
 * - photo (строка, необязательно)
 *
 * Продукт (Product) содержит
 * - id (строка)
 * - name (строка)
 * - photo (строка)
 * - desc (строка, необязательно)
 * - createdAt (строка)
 * - oldPrice (число, необязательно)
 * - price (число)
 * - category (Категория)
 *
 * Операция (Operation) может быть либо тратой (Cost), либо доходом (Profit)
 *
 * Трата (Cost) содержит
 * - id (строка)
 * - name (строка)
 * - desc (строка, необязательно)
 * - createdAt (строка)
 * - amount (число)
 * - category (Категория)
 * - type ('Cost')
 *
 * Доход (Profit) содержит
 * - id (строка)
 * - name (строка)
 * - desc (строка, необязательно)
 * - createdAt (строка)
 * - amount (число)
 * - category (Категория)
 * - type ('Profit')
 * */

export type Category = {
    id: string;
    name: string;
    photo?: string;
};

export type Product = {
    id: string;
    name: string;
    photo: string;
    desc?: string;
    createdAt: string;
    oldPrice?: number;
    price: number;
    category: Category;
};

export type Cost = {
    id: string;
    name: string;
    desc?: string;
    createdAt: string;
    amount: number;
    category: Category;
    type: 'Cost';
};

export type Profit = {
    id: string;
    name: string;
    desc?: string;
    createdAt: string;
    amount: number;
    category: Category;
    type: 'Profit';
};

export type Operation = Cost | Profit;

const randomId = (): string => `${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 10)}`;

const randomInt = (minInclusive: number, maxInclusive: number): number =>
    Math.floor(Math.random() * (maxInclusive - minInclusive + 1)) + minInclusive;

const randomBool = (): boolean => Math.random() > 0.5;

const pick = (items: string[]): string => items[randomInt(0, items.length - 1)];


const makeCategory = (): Category => {
    const name = pick(['Food', 'Transport', 'Health', 'Education', 'Home', 'Electronics', 'Clothes', 'Entertainment']);

    return {
        id: randomId(),
        name,
        photo:
            `https://picsum.photos/seed/${encodeURIComponent(name)}/${randomInt(120, 160)}/${randomInt(120, 160)}`,
    };
};

const makeTitle = (kind: 'product' | 'operation'): string => {
    if (kind === 'product') {
        return pick(['Coffee', 'Tea', 'Chocolate', 'Notebook', 'Headphones', 'Backpack', 'Chair', 'Lamp']);
    }

    return pick(['Payment', 'Refund', 'Subscription', 'Salary', 'Transfer', 'Purchase', 'Bonus', 'Fee']);
};

/**
 * Создает случайный продукт (Product).
 * Принимает дату создания (строка)
 * */
export const createRandomProduct = (createdAt: string): Product => {
    const category = makeCategory();
    const price = randomInt(50, 25_000);
    const oldPriceValue = price + randomInt(10, 1000);

    return {
        id: randomId(),
        name: makeTitle('product'),
        photo: `https://picsum.photos/seed/${randomId()}/${randomInt(240, 320)}/${randomInt(240, 320)}`,
        desc: 'Popular item, limited stock.',
        createdAt,
        oldPrice: oldPriceValue,
        price,
        category,
    };
};

/**
 * Создает случайную операцию (Operation).
 * Принимает дату создания (строка)
 * */
export const createRandomOperation = (createdAt: string): Operation => {
    const category = makeCategory();
    const base = {
        id: randomId(),
        name: makeTitle('operation'),
        desc: 'Autogenerated operation.',
        createdAt,
        amount: randomInt(10, 200_000),
        category,
    };

    if (randomBool()) {
        return { ...base, type: 'Cost' };
    }

    return { ...base, type: 'Profit' };
};
